export const mockData = {
  nodes: [
    { id: "1", title: "The Struggle for AI’s Recognition", authors: "Rosalie Waelen,  Michał Wieczorek ", year: "2022" },
    { id: "2", title: "Research suggests women remain locked out of top roles in media and entertainment. A more diverse cast is required.", authors: "Beard, L., Dunn, J., Huang, J. &, Krivkovich, A.", year: "2021" },
    { id: "3", title: "Gender shades: Intersectional accuracy disparities in commercial gender classification.", authors: "Buolamwini, J., & Gebru, T.", year: "2018" },
    { id: "4", title: "Taking another’s view: Ambivalent implications.", authors: "Butler, J.", year: "2008" },
    { id: "5", title: "Recognition and the social bond: A response to Axel Honneth.", authors: "Butler, J.", year: "2021" },
    { id: "6", title: "Gender shades: Intersectional accuracy disparities in commercial gender classification.", authors: "Buolamwini, J., & Gebru, T.", year: "2018" },
    { id: "7", title: "The whiteness of AI. Philosophy and Technology", authors: "Cave, S., & Dihal, K.", year: "2020" },
    { id: "8", title: "Algorithmic censorship by social platforms: Power and resistance.", authors: "Cobbe, J.", year: "2020" },
    { id: "9", title: "Atlas of AI: Power, politics, and the planetary costs of artificial intelligence. Yale University Press", authors: "Crawford, K.", year: "2021" },
    { id: "10", title: "Bias in computer systems.", authors: "Friedman, B., & Nissenbaum, H.", year: "1996" },
    { id: "11", title: "the struggle for recognition, and robots.", authors: "Gertz, N. ", year: "2018" },
    { id: "12", title: "The struggle for recognition: The moral grammar of social conflicts. ", authors: "Honneth, A.", year: "1996" },
    
    { id: "13", title: "Algorithmic Censorship by Social Platforms: Power and Resistance", authors: "Jennifer Cobbe", year: "2021" },
    { id: "14", title: "Declaration of the Independence of Cyberspace.", authors: "Barlow, J. P", year: "1996" },
    { id: "15", title: "The social power of algorithms.", authors: "Beer, D.", year: "2017" },
    { id: "16", title: "Instagram’s shadow ban on vaguely ‘inappropriate’ content is plainly sexist", authors: "Cook, J..", year: "2019" },
    { id: "17", title: "ree speech and safe spaces: how moderation policies shape online discussion spaces", authors: "Gibson, A.. ", year: "2019" },
    { id: "18", title: "The politics of ‘platforms’", authors: "Gillespie, T.", year: "2010" },
    { id: "19", title: "The future of online content personalisation: technology, law and digital freedoms. ", authors: "Graber, C. B..", year: "2016" },
  ],

  links: [
    { source: "1", target: "2" },
    { source: "1", target: "3" },
    { source: "1", target: "4" },
    { source: "1", target: "5" },
    { source: "1", target: "6" },
    { source: "1", target: "7" },
    { source: "1", target: "8" },
    { source: "1", target: "9" },
    { source: "1", target: "10" },
    { source: "1", target: "11" },
    { source: "1", target: "12" },
    { source: "1", target: "13" },

    { source: "13", target: "14" },
    { source: "13", target: "15" },
    { source: "13", target: "16" },
    { source: "13", target: "17" },
    { source: "13", target: "18" },
    { source: "13", target: "19" },
  ],
};
